name: iec_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # Dependências do Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7  # <--- NOVO (Para salvar fotos)
  
  # Utilitários
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2       # <--- NOVO (Para abrir câmera/galeria)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true

  # Configuração dos Assets (Arquivos)
  assets:
    - assets/json/ARA.json
    - assets/json/hinos.json