name: iec_app
description: "App da Igreja Evangélica Congregacional em Moreno."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  # Internacionalização
  intl: ^0.19.0

  # --- HTTP (ESSENCIAL PARA ENVIAR NOTIFICAÇÕES) ---
  http: ^1.2.0

  # --- FIREBASE ---
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  firebase_messaging: ^15.1.6
  
  # --- PDF e IMPRESSÃO ---
  pdf: ^3.10.4
  printing: ^5.12.0

  # --- UTILITÁRIOS ---
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  
  # --- UI e FONTES ---
  google_fonts: ^6.1.0
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.2.5
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Gerador de ícones
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/json/ARA.json
    - assets/json/hinos.json
    - assets/images/

# --- CONFIGURAÇÃO DO ÍCONE ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#0D47A1"
    theme_color: "#0D47A1"